server:
  port: 8081

mybatis.type-aliases-package: com.onlineExam.model
mybatis:
  mapperLocation: classpath:mapper/*.xml

spring:
  datasource:
    url: jdbc:mysql://119.3.181.121:3306/onlineexam?useUnicode=true&characterEncoding=utf8&userSSL=false
    username: root
    password: Czbank@2019
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQueryS: LECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20

#Redis
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    pool.max-active: 8
    pool.max-wait: -1
    pool.max-idle: 8
    pool.min-idle: 0
logging:

  path: /logs
  level:
    root: info
    com.onlineExam: info
    org.springframework.jdbc: info
    org.apach.http: info

